name: ci

on: push

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Set timeout to 60 minutes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      -name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          stepsrun
      - if: matrix.build-mode == 'manual'
        shell: bash
        run: |
          echo 'If you are using a "manual" build mode for one or more of the' \
            'languages you are analyzing, replace this with the commands to build' \
            'your code, for example:'
          echo '  make bootstrap'
          echo '  make release'
          exit 1
  
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dulaaaaluuuuuu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dulaaaaluuuuuu/final:kProjek
