name: ci

on: push

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Set timeout to 60 minutes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dulaaaaluuuuuu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dulaaaaluuuuuu/final:kProjek
